name       : fifechan
version    : 0.1.5
release    : 7
source     :
    - https://github.com/fifengine/fifechan/archive/0.1.5.tar.gz : 29be5ff4b379e2fc4f88ef7d8bc172342130dd3e77a3061f64c8a75efe4eba73
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Fifechan is a lightweight cross platform GUI library written in C++
description: |
    Fifechan is a lightweight cross platform GUI library written in C++ specifically designed for games.
builddeps  :
    - pkgconfig(allegro-5)
    - pkgconfig(gl)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_ttf)
setup      : |
    mkdir _build
    cd _build
    %cmake -DENABLE_SDL_CONTRIB=1 ..
build      : |
    cd _build
    %make
install    : |
    cd _build
    %make_install
